version: 2.1

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
jobs:

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  build_run_log:
    docker:
      - image: openjdk:8
    steps:
      - run:
          name: Foo
          command: echo "Building"

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  deploy_run_log:
    docker:
      - image: openjdk:8
    steps:
      - run:
          name: Bar
          command: echo "Deploying"

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
workflows:
  version: 2
  build_and_deploy_run_log:
    jobs:
      - build_run_log
      - deploy_run_log:
          requires:
            - build_run_log
