version: 2.1

#
# REQUIRED ENVIRONMENT VARIABLES:
# In Jobs > run-log settings (gear icon) > Environment Variables, set up:
#
#   - AWS_ACCESS_KEY_ID
#   - AWS_S3_BUCKET_NAME_WEB_ASSETS
#   - AWS_SECRET_ACCESS_KEY
#   - BACKEND_SECRET_CONGIF_GUID
#   - PRODUCTION_SERVER_DOMAIN
#   - PRODUCTION_SERVER_USER
#

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
jobs:

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  build_run_log_frontend:

    parameters:

      python_version:
        description: Python version
        type: string
        default: "3.8"

      yarn_version:
        description: Yarn version
        type: string
        default: 0.27.5

      aws_region:
        description: AWS region
        type: string
        default: "us-east-1"

    docker:
      - image: circleci/python:<< parameters.python_version >>-node

    environment:
      - AWS_DEFAULT_REGION: << parameters.aws_region >>

    steps:
      - run:
          name: Debugging
          command: |
            npm -v
            node -v
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version << parameters.yarn_version >>
            yarn -v
      - run:
          name: Install AWS CLI
          command: pip3 install awscli --user
      - checkout
      - run:
          name: Create frontend configuration
          command: |
            FE_CONFIG=frontend/src/config.json
            cat \<<- EOF > "${FE_CONFIG}"
            {
              "baseUrl": "${PRODUCTION_SERVER_DOMAIN}"
            }
            EOF
            if [ ! -e "${FE_CONFIG}" ]; then
              echo "File not found: ${FE_CONFIG}"
              exit 1
            else
              echo "Printing ${FE_CONFIG}:"
              cat "${FE_CONFIG}"
            fi
      - restore_cache:
          key: npm-cache-{{ .Branch }}-v4--{{ checksum "frontend/package.json" }}
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn && yarn build
            cd ..
      - save_cache:
          key: npm-cache-{{ .Branch }}-v4--{{ checksum "frontend/package.json" }}
          paths:
            - frontend/node_modules
      - run:
          name: View web assets
          command: ls frontend/dist
      # TODO: Set up s3 bucket, if not exists, using Terraform
      # TODO: Branch-specific s3 buckets
      - run:
          name: Sync web assets with S3
          command: aws s3 sync frontend/dist s3://${AWS_S3_BUCKET_NAME_WEB_ASSETS}

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
workflows:
  version: 2
  build_and_deploy_run_log:
    jobs:
      - build_run_log_frontend
