version: 2.1

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
jobs:

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  build_run_log_frontend:

    parameters:

      node_version:
        description: NodeJS version
        type: string
        default: 9.10.1

      yarn_version:
        description: Yarn version
        type: string
        default: 0.27.5

    docker:
      - image: circleci/node:<< parameters.node_version >>

    environment:
      WEB_ASSETS_DIST: backend/src/main/resources/frontend-dist

    steps:
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version << parameters.yarn_version >>
            yarn -v
      - checkout
      - run:
          name: Create frontend configuration
          command: |
            FE_CONFIG=frontend/src/config.json
            cat \<<- EOF > "${FE_CONFIG}"
              {
                "baseUrl": "${PRODUCTION_SERVER_DOMAIN}"
              }
            EOF
            if [ ! -e "${FE_CONFIG}" ]; then
              echo "File not found: ${FE_CONFIG}"
              exit 1
            else
              echo "Printing ${FE_CONFIG}:"
              cat "${FE_CONFIG}"
            fi
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn && yarn build
            cd ..
      - run:
          name: Prepare web assets directory
          command: |
            if [ ! -d "$WEB_ASSETS_DIST" ]; then
              mkdir -p "$WEB_ASSETS_DIST"
            fi
      - run:
          name: Copy web assets
          command: cp frontend/dist/* "$WEB_ASSETS_DIST"
      - run:
          name: View web assets
          command: ls "$WEB_ASSETS_DIST"
      - persist_to_workspace:
          root: .
          paths:
            - backend/

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  build_run_log_backend:

    parameters:

      sbt_version:
        description: sbt version
        type: string
        default: 1.0.4

    docker:
      - image: openjdk:8

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install sbt
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-<< parameters.sbt_version >>.deb https://dl.bintray.com/sbt/debian/sbt-<< parameters.sbt_version >>.deb
            dpkg -i sbt-<< parameters.sbt_version >>.deb
            rm sbt-<< parameters.sbt_version >>.deb
            apt-get update
            apt-get install -y sbt
            apt-get clean && apt-get autoclean
      - run:
          name: Create backend configuration
          command: |
            BE_CONFIG=backend/src/main/resources/application.conf
            cat \<<- EOF > "${BE_CONFIG}"
              {
                secret = "${BACKEND_SECRET_CONGIF_GUID}"
              }
            EOF
            if [ ! -e "${BE_CONFIG}" ]; then
              echo "File not found: ${BE_CONFIG}"
              exit 1
            else
      - run:
          name: Run backend unit tests
          command: echo "TODO"
      - run:
          name: Build JAR
          command: |
            cd backend
            sbt assembly
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - backend/

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  deploy_run_log:

    docker:
      - image: openjdk:8

    steps:
      - add_ssh_keys:
          fingerprints:
            - "71:a6:69:31:f9:43:92:0e:42:4c:b0:cf:b4:03:ff:6e"
      - attach_workspace:
          at: .
      - run:
          name: Printing environment variables
          command: |
            echo PRODUCTION_SERVER_USER=$PRODUCTION_SERVER_USER
            echo PRODUCTION_SERVER_DOMAIN=$PRODUCTION_SERVER_DOMAIN
      - run:
          name: Adding server to known_hosts
          command: |
            ssh-keygen -F ${PRODUCTION_SERVER_DOMAIN} >/dev/null || ssh-keyscan -H ${PRODUCTION_SERVER_DOMAIN} >> ~/.ssh/known_hosts
      # TODO: shouldn't assume run-log version 0.0.1
      # TODO: shouldn't assume Scala version 2.12
      - run:
          name: Deploying to server
          command: |
            scp backend/target/scala-2.12/run-log-assembly-0.0.1-SNAPSHOT.jar ${PRODUCTION_SERVER_USER}@${PRODUCTION_SERVER_DOMAIN}:/home/ec2-user/run-log/run-log.latest.jar
      - run:
          name: Restarting server
          command: |
            ssh -f ${PRODUCTION_SERVER_USER}@${PRODUCTION_SERVER_DOMAIN} "sudo sh -c 'nohup /home/${PRODUCTION_SERVER_USER}/bin/restart-run-log > /dev/null 2>&1 &'"

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
workflows:
  version: 2
  build_and_deploy_run_log:
    jobs:
      - build_run_log_frontend
      - build_run_log_backend:
          requires:
            - build_run_log_frontend
      - deploy_run_log:
          requires:
            - build_run_log_backend
