version: 2.1

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
jobs:

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  build_run_log:
    docker:
      - image: openjdk:8
      environment:
        WEB_ASSETS_DIST: run-log/backend/src/main/resources/frontend-dist
    steps:
      - run:
          name: Build frontend
          command: |
            cd run-log/frontend
            yarn && yarn build
      - run:
          name: Copy web assets
          command: |
            cd ../..
            if [! -d "$WEB_ASSETS_DIST" ]; then
              mkdir "$WEB_ASSETS_DIST"
            fi
            cp run-log/frontend/dist/* "$WEB_ASSETS_DIST"
      - run:
          name: View web assets
          command: ls "$WEB_ASSETS_DIST"
      - run:
        name: Run backend unit tests
        command: echo "TODO"
      - run:
        name: Build JAR
        command: sbt assembly

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  deploy_run_log:
    docker:
      - image: openjdk:8
    steps:
      - run:
          name: Bar
          command: echo "Deploying"

# = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
workflows:
  version: 2
  build_and_deploy_run_log:
    jobs:
      - build_run_log
      - deploy_run_log:
          requires:
            - build_run_log
